# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  light_recessed:    "\U000F179B"

  icon_font: light40
  time_font: dseg_60
  date_font: roboto48
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  time_color: "powderblue"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 4s

  # Screen goes to sleep
  screen_sleep_hour: '3'
  screen_sleep_minute: '0'

  # Screen wakes up at 5:30am
  screen_wake_hour: '4'
  screen_wake_minute: '0'

  # Button 1 is a local relay
  button_1_name: "Dining"
  button_1_id: dining_light
  button_1_icon: $light_recessed
  button_1_device: "internal_relay_2"

  # Button 2 is a local relay
  button_2_name: "Kitchen"
  button_2_id: kitchen_light
  button_2_icon: $track_light
  button_2_device: "internal_relay_1"

  # Button 3 is a local relay
  button_3_name: "Outside"
  button_3_id: outside_light
  button_3_icon: $bulkhead_light
  button_3_device: "internal_relay_3"

esphome:
  name: hideout-screen
  friendly_name: Hideout Screen
  comment: "Guition ESP32-4848S040 480px * 480px Smart Screen"  
    
packages:
  # Generic configuration for ESP32 screens
  base: !include modules/common/base.yaml
  globals: !include modules/common/globals.yaml
  wifi: !include modules/common/wifi.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml
  images: !include modules/common/images.yaml
  
  # Harware description file
  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml
  
  # Base settings for LVGL libary
  lvgl_time: !include modules/lvgl/base/lvgl_time_homeassistant.yaml
  lvgl_sensors: !include modules/lvgl/base/lvgl_sensors_base.yaml
  lvgl_base: !include modules/lvgl/base/lvgl_base.yaml

  # Time update script
  lvgl_time_update: !include modules/lvgl/base/lvgl_datetime2_update.yaml
  
  # Update button and relay state from Home Assistant
  button_1_sensor: !include { file: modules/sensors/basic_local_relay_button_state.yaml, vars: { id: 1 } }
  button_2_sensor: !include { file: modules/sensors/basic_local_relay_button_state.yaml, vars: { id: 2 } }
  button_3_sensor: !include { file: modules/sensors/basic_local_relay_button_state.yaml, vars: { id: 3 } }

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
  theme: !include { file: modules/lvgl/base/lvgl_theme.yaml }
  page_wrap: true

# Boot screen
  top_layer: !include { file: modules/lvgl/screens/boot_screen.yaml }

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: ROW_WRAP
      width: 100%
      bg_color: black
      bg_opa: cover
      pad_all: 5
      widgets: # Include all the buttons
        - button: !include { file: modules/lvgl/buttons/basic_local_relay_button.yaml, vars: { id: 1, height: $button_height_double } }
        - button: !include { file: modules/lvgl/buttons/basic_local_relay_button.yaml, vars: { id: 2, height: $button_height_double } }
        - button: !include { file: modules/lvgl/buttons/basic_local_relay_button.yaml, vars: { id: 3, height: $button_height_double } }
        - obj: !include { file: modules/lvgl/datetime/date.yaml, vars: { id: 1, height: $button_height_double } }
        - obj: !include { file: modules/lvgl/datetime/time.yaml, vars: { id: 1, height: $button_height_double } }
        - obj: !include { file: modules/lvgl/weather/weather.yaml, vars: { id: 1, height: $button_height_double } }
