#-------------------------------------------
# Waveshare ESP32-S3 Touch LCD 4" hardware configuration file

esphome:
  min_version: 2024.11.0
  name: "${name}"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

preferences:
  flash_write_interval: 1min

psram:
  mode: octal
  speed: 80MHz

logger:

api:
  reboot_timeout: 0s
  on_client_connected:
    - lvgl.widget.hide: boot_screen

i2c:
  - id: tp_i2c
    sda: 15
    scl: 7
    scan: true
    frequency: 400kHz

sensor:
  - platform: htu21d
    model: htu21d
    temperature:
      id: temperature_id
      name: "Temperature"
    humidity:
      id: humidity_id
      name: "Humidity"
    heater:
      id: header_id
      name: "Heater"

pca9554:
  id: expander

touchscreen:
  platform: gt911
  i2c_id: tp_i2c
  id: my_touchscreen
  reset_pin:
    pca9554: expander
    number: 0
  interrupt_pin: 16


light:
  - platform: monochromatic
    output: backlight_output
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 4s
    gamma_correct: 1.8

switch:
  - platform: gpio
    id: buzzer
    pin:
      pca9554: expander
      number: 5
      mode:
        output: true

output:
  - platform: ledc
    id: backlight_output
    pin: 44
    frequency: 1220Hz
    inverted: true
    min_power: 15%

spi:
  - id: lcd_spi
    clk_pin: GPIO2
    mosi_pin: GPIO1
    
display:
  platform: st7701s
  id: st7701s_disp
  update_interval: never
  auto_clear_enabled: false
  data_rate: 2MHz
  spi_mode: MODE3
  color_order: BGR
  invert_colors: true
  dimensions:
    width: 480
    height: 480
  transform:
    mirror_x: false
    mirror_y: false
  cs_pin: GPIO42
  de_pin: GPIO40
  hsync_pin: GPIO38
  vsync_pin: GPIO39
  pclk_pin: GPIO41
  pclk_frequency: 12MHz
  pclk_inverted: false
  data_pins:
    red:
      - GPIO46       #r1
      - GPIO3        #r2
      - GPIO8      #r3
      - GPIO18       #r4
      - GPIO17       #r5
    green:
      - GPIO14       #g0
      - GPIO13       #g1
      - GPIO12       #g2
      - GPIO11       #g3
      - GPIO10       #g4
      - GPIO9     #g5
    blue:
      - GPIO5        #b1
      - GPIO45       #b2
      - GPIO48       #b3
      - GPIO47       #b4
      - GPIO21       #b5`
